sudo: required
language: csharp

mono: none
dotnet: 2.0.0

script: 
  - dotnet restore ./src/ReactiveDomain.sln
  - dotnet msbuild ./src/ReactiveDomain.sln
  - dotnet test ./src/ReactiveDomain.Messaging.Tests/ReactiveDomain.Messaging.Tests.csproj
  - dotnet test ./src/ReactiveDomain.Foundation.Tests/ReactiveDomain.Foundation.Tests.csproj  
  - dotnet test ./src/ReactiveDomain.PrivateLedger.Tests/ReactiveDomain.PrivateLedger.Tests.csproj
  - dotnet test ./src/ReactiveDomain.Transport.Tests/ReactiveDomain.Transport.Tests.csproj
  - dotnet nuget push ./packages/ReactiveDomain.Core.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.Foundation.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.Messaging.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.Persistence.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.PrivateLedger.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.Testing.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.Transport.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.UI.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  - dotnet nuget push ./packages/ReactiveDomain.UI.Testing.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"  