sudo: required
language: csharp
os: windows
mono: none

env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
  - MSBUILD_EXE="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MsBuild.exe"

branches:
  only:
    - master
    - /.*/

addons:
  apt:
    packages:
      - powershell

before_script:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
  - powershell -executionpolicy unrestricted -File ./tools/CheckAssemblyVersion.ps1
  
script: 
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_DIR
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_EVENT_TYPE
  - echo $STABLE
  - dotnet restore ./src/ReactiveDomain.sln
  - echo $MSBUILD_EXE
  - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MsBuild.exe" ./src/ReactiveDomain.sln -p:Configuration=Debug
  - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MsBuild.exe" ./src/ReactiveDomain.sln -p:Configuration=Release
  - dotnet test ./src/ReactiveDomain.Messaging.Tests/ReactiveDomain.Messaging.Tests.csproj
  - dotnet test ./src/ReactiveDomain.Foundation.Tests/ReactiveDomain.Foundation.Tests.csproj  
  - dotnet test ./src/ReactiveDomain.PrivateLedger.Tests/ReactiveDomain.PrivateLedger.Tests.csproj
  - dotnet test ./src/ReactiveDomain.Transport.Tests/ReactiveDomain.Transport.Tests.csproj

after_success:
  - powershell -executionpolicy unrestricted -File ./tools/CreateNuget.ps1
